- name: Vagrant + VirtualBoxのインストール
  hosts: cybersec
  vars:
    user: vagrant
  remote_user: "{{user}}"
  tasks:
    - name: apt update
      become: yes
      apt:
        update_cache: yes
    - name: apt upgrade
      become: yes
      apt:
        upgrade: dist
    - name: install VirtualBox
      become: yes
      apt:
        name: "{{packages}}"
      vars:
        packages:
          - virtualbox
    - name: download Vagrant
      get_url:
        url: https://releases.hashicorp.com/vagrant/2.2.8/vagrant_2.2.8_x86_64.deb
        dest: /tmp
    - name: install Vagrant
      become: yes
      apt:
        deb: /tmp/vagrant_2.2.7_x86_64.deb
    - name: fetch the box of OpenBSD
      command: vagrant box add generic/openbsd6 --provider virtualbox
